Repository Alwatr/nginx, pull requests merged in 2023-11, with the labels that each got.

#4 refactor: base on alwatr/nginx
  nginx-pwa/.dockerignore
  nginx-pwa/Dockerfile
  nginx-pwa/etc/nginx/entrypoint.d/30-envsubst-on-config-js.sh
  nginx-pwa/etc/nginx/templates/location.d/90-pwa.conf.template
  nginx-ws/.dockerignore
  nginx-ws/Dockerfile
  nginx-ws/etc/nginx/templates/location.d/90-ws.conf.template
  nginx/.dockerignore
Labels: enhancement, bugfix

#8 chore(ci/publish-container): disable check file changed in workflow dispatch
  .github/workflows/publish-container.yml
Labels: ci

#7 feat(nginx-core/redirect): implement redirect
  .gitignore
  nginx-core/Dockerfile
  nginx-core/etc/nginx/templates/20-http-include.conf.template
  nginx-core/etc/nginx/templates/http.d/90-redirect-map.conf.template
  nginx-core/etc/nginx/templates/location.d/40-force-domain.conf.template
  nginx-core/etc/nginx/templates/location.d/50-redirect-uri.conf.template
  nginx-core/etc/nginx/templates/redirect.d/example.map.template
  nginx-core/etc/nginx/templates/server.d/00-default.conf.template
Labels: new-feature

#9 feat: enhance and update workdir and document root
  .github/workflows/publish-container.yml
  README.md
  nginx-cdn/.dockerignore
  nginx-cdn/Dockerfile
  nginx-core/.dockerignore
  nginx-core/Dockerfile
  nginx-core/data/_error.html
  nginx-core/data/index.html
  nginx-core/etc/nginx/templates/location.d/10-error-page.conf.template
  nginx-pwa/.dockerignore
  nginx-pwa/Dockerfile
  nginx-pwa/etc/nginx/entrypoint.d/30-envsubst-on-config-js.sh
  nginx-ws/.dockerignore
  nginx-ws/Dockerfile
  nginx/.dockerignore
  nginx/Dockerfile
Labels: major, breaking-change

#10 feat(nginx-json): new nginx optimized for serving JSON content effici…
  nginx-json/.dockerignore
  nginx-json/Dockerfile
  nginx-json/data/error.json
  nginx-json/etc/nginx/templates/location.d/10-error-page.conf.template
  nginx-json/etc/nginx/templates/location.d/90-home-json.conf.template
Labels: new-feature
