Repository Alwatr/nginx, pull requests merged in 2023-12, with the labels that each got.

#14 fix(nginx-json): error page file name
  .github/workflows/publish-container.yml
  nginx-json/data/_error.json
Labels: bugfix

#16 feat(nginx-json): internal error template
  nginx-json/Dockerfile
  nginx-json/data/_error.json
  nginx-json/etc/nginx/templates/location.d/10-error-page.conf.template
Labels: minor, bugfix

#17 fix(json): error json status code
  nginx-json/etc/nginx/templates/location.d/10-error-page.conf.template
Labels: bugfix

#18 feat: Add default data and copy in runtime entrypoint for error pages
  nginx-cdn/.dockerignore
  nginx-cdn/Dockerfile
  nginx-core/.dockerignore
  nginx-core/Dockerfile
  nginx-core/default-data/_error.html
  nginx-core/default-data/index.html
  nginx-core/etc/nginx/entrypoint.d/90-cleanup-conf.sh
  nginx-json/.dockerignore
  nginx-json/Dockerfile
  nginx-json/default-data/_error.json
  nginx-json/etc/nginx/templates/location.d/10-error-page.conf.template
  nginx-pwa/.dockerignore
  nginx-pwa/Dockerfile
  nginx-pwa/etc/nginx/entrypoint.d/90-envsubst-on-config-js.sh
  nginx-ws/.dockerignore
  nginx-ws/Dockerfile
  nginx/.dockerignore
  nginx/etc/nginx/entrypoint.d/30-copy-default-data.sh
Labels: minor, new-feature, bugfix

#19 Fix default data copy issue
  nginx/etc/nginx/entrypoint.d/30-copy-default-data.sh
Labels: bugfix
